name: deploy-payment-project

x-postgres-common:
  &postgres-common
  image: postgres:17-alpine
  restart: always
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  api:
    build: ../payment_project/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../payment_project:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  migration_handler:
    build: ../payment_project/
    command: |
      bash -c "
      python manage.py makemigrations --merge --noinput;
      python manage.py migrate
      "
    volumes:
      - ../payment_project:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    <<: *postgres-common
    ports:
      - "5432:5432"
    environment:
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=postgres"
    - "POSTGRES_DB=paymentproject"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5

  celery:
    build: ../payment_project/
    command: celery -A payment_project worker -l info
    volumes:
      - ../payment_project:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  pg-anon-scheduler:
    build:
      context: ../db-anon
    image: pg-anon-scheduler:latest
    environment:
      - PGHOST=db
      - PGDATABASE=paymentproject
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - INTERVAL_SECONDS=3600      # rodar a cada 3600s (1h). ajuste conforme quiser
      - RETENTION_COUNT=168        # mantém 168 arquivos (ex: ~7 dias se hourly)
      - MASKING_RULES=/masks/masking_rules.sql
      - DUMP_DIR=/dumps
      - CONFIG_FILE=/config/config.txt
    volumes:
      - ./db/dumps:/dumps
      - ./db/masking_rules.sql:/masks/masking_rules.sql:ro
      - ./db/config.anon.txt:/config/config.txt
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    restart: always

volumes:
  postgres_data:
  postgres_replica_data:

networks:
  default:
    name: payment-project
    driver: bridge
